databases:
  - name: wandermere-medicine.com
    databaseName: wandermere_medicine
    user: wandermere_medicine_user

services:
  - type: web
    name: wandermere-medicine.com
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wandermere-family-medicine.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wandermere_medicine
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4