# Generated by Django 4.1.3 on 2022-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='title',
            field=models.CharField(default='Family Practice Doctor', max_length=100),
            preserve_default=False,
        ),
    ]
