# Generated by Django 4.1.6 on 2023-02-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0005_alter_provider_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="image",
        ),
    ]
